server:
  port: 8080

spring:
  application:
    name: webflux-course
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@webfluxcoursecluster.wwdirxj.mongodb.net/${MONGODB_DATABASE}?retryWrites=true&w=majority
      auto-index-creation: true
